export default {
  login: "paudeldipesh",
  id: 122140496,
  node_id: "U_kgDOB0e3UA",
  avatar_url: "https://avatars.githubusercontent.com/u/122140496?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/paudeldipesh",
  html_url: "https://github.com/paudeldipesh",
  followers_url: "https://api.github.com/users/paudeldipesh/followers",
  following_url:
    "https://api.github.com/users/paudeldipesh/following{/other_user}",
  gists_url: "https://api.github.com/users/paudeldipesh/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/paudeldipesh/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/paudeldipesh/subscriptions",
  organizations_url: "https://api.github.com/users/paudeldipesh/orgs",
  repos_url: "https://api.github.com/users/paudeldipesh/repos",
  events_url: "https://api.github.com/users/paudeldipesh/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/paudeldipesh/received_events",
  type: "User",
  site_admin: false,
  name: "Dipesh Paudel",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "HELLO WORLD",
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: "2023-01-07T04:47:30Z",
  updated_at: "2023-11-08T08:43:57Z",
};
